Trivia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('trivia/', include("trivia.urls"))
]

trivia/urls.py
from django.urls import path

from . import views

app_name = "trivia"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

trivia/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

class Category(models.Model):
    category = models.CharField(max_length=40)

    def __str__(self):
        return self.category

class Question(models.Model):
    class Type(models.TextChoices):
        MULTIPLE_CHOICE = "Multiple Choice"
        TRUE_FALSE = "True or False"

    class Difficulty(models.TextChoices):
        EASY = "E", _("Easy")
        MEDIUM = "M", _("Medium")
        HARD = "H", _("Hard")

    true_or_false = models.BooleanField(default=False)

    difficulty = models.CharField(max_length=2, choices=Difficulty, default=Difficulty.MEDIUM)
    category = models.ManyToManyField(Category)
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.question_text
    
class Choice(models.Model):
    question_ID = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=80)
    correct = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if self.correct:
            # Ensure that no other record has correct set to True
            Choice.objects.filter(correct=True).exclude(pk=self.pk).update(correct=False)
        super().save(*args, **kwargs)
    def __str__(self):
        return self.choice_text

    
class User(models.Model):
    name = models.CharField(max_length=20)
    correctlyAnswered = models.PositiveIntegerField(default=0)
    incorrectlyAnswered = models.PositiveIntegerField(default=0)

trivia/views.py
from django.db.models import F
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Question, Choice

class IndexView(generic.ListView):
    template_name = "trivia/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = "trivia/detail.html"


class ResultsView(generic.DetailView):
    model = Question
    template_name = "trivia/results.html"


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "trivia/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("trivia:results", args=(question.id,)))
    
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "trivia/results.html", {"question": question})

trivia/templates/trivia/detail.html
<form action="{% url 'trivia:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
    </form>

trivia/templates/trivia/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'trivia:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

trivia/templates/trivia/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'trivia:detail' question.id %}">Vote again?</a>